services:
  api:
    build:
      context: .
      dockerfile: /Dockerfile
    image: prueba_tecnica_imaginemos
    ports:
      - "8081:8081"
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: newpassword
      POSTGRES_DB: PruebaTécnicaImaginemos
    ports:
      - "5432:5432"

